extern crate core;

mod tool;
mod beatmap;
mod osu_pp;
mod osu_performance_attributes;
mod osu_difficulty_attributes;
mod osu_stars;
mod osu_strains;
mod taiko_pp;
mod taiko_performance_attributes;
mod taiko_difficulty_attributes;
mod taiko_stars;
mod taiko_strains;
mod catch_pp;
mod catch_performance_attributes;
mod catch_difficulty_attributes;
mod catch_stars;
mod catch_strains;
mod maina_pp;
mod mania_performance_attributes;
mod mania_difficulty_attributes;
mod mania_stars;
mod mania_strains;