[package]
name = "rosu-pp-jni"
version = "0.0.1"
authors = ["cssxsh"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.20.0"
rosu-pp = "0.9.3"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"